# python -m anamod.simulation.simulation -num_instances 20000 -model_type regressor -analysis_type temporal -sequence_length 20 -sequences_independent_of_windows 0 -perturbation shuffling -noise_multiplier auto -num_features 10 -fraction_relevant_features 0.5 -num_shuffling_trials 1 -seed 13531 -output_dir /Users/akshaysood/Documents/projects/anamod_visualize/notebooks/simulation1
# Unable to get non-zero FDR, though observed FDR of 0.33 with 100000 instances on BCG.

# Trying different config with high FDR (0.5), reusing synthesized data
# python -m anamod.simulation.simulation -num_instances 10000 -model_type regressor -analysis_type temporal -sequence_length 50 -sequences_independent_of_windows 0 -perturbation shuffling -noise_multiplier auto -num_features 30 -fraction_relevant_features 0.33 -num_shuffling_trials 1 -seed 13531 -condor 1 -shared_filesystem 1 -avoid_bad_hosts 1 -features_per_worker 1 -output_dir simulation_demo -cleanup 0 -compile_results_only 1
# python -m anamod.simulation.simulation -num_instances 50000 -model_type regressor -analysis_type temporal -sequence_length 20 -sequences_independent_of_windows 0 -perturbation shuffling -noise_multiplier auto -num_features 10 -fraction_relevant_features 0.5 -num_shuffling_trials 1 -seed 13531 -cleanup 0 -condor 0 -shared_filesystem 1 -avoid_bad_hosts 1 -features_per_worker 1 -output_dir simulation_demo_test3

# Permutation-based p-value; feature 4 is irrelevant but gets low p-value, why?
# python -m anamod.simulation.simulation -num_instances 100 -model_type regressor -analysis_type temporal -sequence_length 50 -sequences_independent_of_windows 0 -perturbation shuffling -noise_multiplier auto -num_features 30 -fraction_relevant_features 0.33 -num_shuffling_trials 50 -seed 13531 -condor 0 -shared_filesystem 1 -avoid_bad_hosts 1 -features_per_worker 1 -output_dir simulation_demo_toy -cleanup 0 -skip_synthesis 1

# Changed instance permutations to use shuffling
# python -m anamod.simulation.simulation -num_instances 100 -model_type regressor -analysis_type temporal -sequence_length 50 -sequences_independent_of_windows 0 -perturbation shuffling -noise_multiplier auto -num_features 30 -fraction_relevant_features 0.33 -num_shuffling_trials 50 -seed 13531 -condor 0 -shared_filesystem 1 -avoid_bad_hosts 1 -features_per_worker 1 -output_dir simulation_demo_toy2 -cleanup 0 -skip_synthesis 1

# python -m anamod.simulation.simulation -num_instances 100 -model_type regressor -analysis_type temporal -sequence_length 50 -sequences_independent_of_windows 0 -perturbation shuffling -noise_multiplier auto -num_features 30 -fraction_relevant_features 0.33 -num_shuffling_trials 500 -seed 13531 -condor 0 -shared_filesystem 1 -avoid_bad_hosts 1 -features_per_worker 1 -output_dir simulation_demo_toy3 -cleanup 0 -skip_synthesis 1
#python -m anamod.simulation.simulation -num_instances 1000 -model_type regressor -analysis_type temporal -sequence_length 50 -sequences_independent_of_windows 0 -perturbation shuffling -noise_multiplier auto -num_features 30 -fraction_relevant_features 0.33 -num_shuffling_trials 50 -seed 13531 -condor 0 -shared_filesystem 1 -avoid_bad_hosts 1 -features_per_worker 1 -output_dir simulation_demo_toy4 -cleanup 0 -skip_synthesis 1
# python -m anamod.simulation.simulation -num_instances 200 -model_type regressor -analysis_type temporal -sequence_length 50 -sequences_independent_of_windows 0 -perturbation shuffling -noise_multiplier auto -num_features 30 -fraction_relevant_features 0.33 -num_shuffling_trials 50 -seed 13531 -condor 0 -shared_filesystem 1 -avoid_bad_hosts 1 -features_per_worker 1 -output_dir simulation_demo_toy5 -cleanup 0 -skip_synthesis 1
# python -m anamod.simulation.simulation -num_instances 400 -model_type regressor -analysis_type temporal -sequence_length 50 -sequences_independent_of_windows 0 -perturbation shuffling -noise_multiplier auto -num_features 30 -fraction_relevant_features 0.33 -num_shuffling_trials 50 -seed 13531 -condor 0 -shared_filesystem 1 -avoid_bad_hosts 1 -features_per_worker 1 -output_dir simulation_demo_toy6 -cleanup 0 -skip_synthesis 0

# python -m anamod.simulation.simulation -num_instances 400 -sequence_length 50 -num_features 30 -fraction_relevant_features 0.33 -noise_multiplier 0.33 -analysis_type temporal -model_type regressor -sequences_independent_of_windows 0 -perturbation shuffling -num_shuffling_trials 50 -num_interactions 0  -seed 500003 -output_dir temp1 -condor 0 -shared_filesystem 1 -avoid_bad_hosts 1 -features_per_worker 1 -cleanup 0 -skip_synthesis 1


# python -m anamod.simulation.simulation -num_instances 1000 -model_type regressor -analysis_type temporal -sequence_length 50 -sequences_independent_of_windows 0 -perturbation shuffling -noise_multiplier auto -num_features 30 -fraction_relevant_features 0.33 -num_shuffling_trials 50 -seed 13531 -condor 0 -shared_filesystem 1 -avoid_bad_hosts 1 -features_per_worker 1 -output_dir simulation_demo_toy4 -cleanup 0 -skip_synthesis 1 -evaluate_only 1

# python -m anamod.simulation.simulation -num_instances 100 -sequence_length 50 -num_features 30 -fraction_relevant_features 0.33 -noise_multiplier 0.33 -analysis_type temporal -model_type regressor -sequences_independent_of_windows 0 -perturbation shuffling -num_shuffling_trials 10 -num_interactions 0  -seed 500090 -output_dir temp1 -cleanup 0 -num_shuffling_trials 10 -skip_synthesis 1


# Testing weighted average statistic for permutation test
# python -m anamod.simulation.simulation -num_instances 1000 -model_type regressor -analysis_type temporal -sequence_length 50 -sequences_independent_of_windows 0 -perturbation shuffling -noise_multiplier auto -num_features 30 -fraction_relevant_features 0.33 -num_shuffling_trials 50 -seed 13531 -condor 0 -shared_filesystem 1 -avoid_bad_hosts 1 -features_per_worker 1 -output_dir simulation_demo_toy4 -cleanup 0 -skip_synthesis 1
# Increased the number of permutations
# python -m anamod.simulation.simulation -num_instances 1000 -model_type regressor -analysis_type temporal -sequence_length 50 -sequences_independent_of_windows 0 -perturbation shuffling -noise_multiplier auto -num_features 30 -fraction_relevant_features 0.33 -num_shuffling_trials 100 -seed 13531 -condor 0 -shared_filesystem 1 -avoid_bad_hosts 1 -features_per_worker 1 -output_dir simulation_demo_toy4 -cleanup 0 -skip_synthesis 1

# Different dir, resynthesize with standard normalization
# python -m anamod.simulation.simulation -num_instances 1000 -model_type regressor -analysis_type temporal -sequence_length 50 -sequences_independent_of_windows 0 -perturbation shuffling -noise_multiplier auto -num_features 30 -fraction_relevant_features 0.33 -num_shuffling_trials 100 -seed 13531 -condor 0 -shared_filesystem 1 -avoid_bad_hosts 1 -features_per_worker 1 -output_dir simulation_demo_toy7 -cleanup 0 -skip_synthesis 1 -evaluate_only 1

# Previous attempt worked with 0 FDR and 1 Power. Trying fewer instances
# python -m anamod.simulation.simulation -num_instances 100 -model_type regressor -analysis_type temporal -sequence_length 50 -sequences_independent_of_windows 0 -perturbation shuffling -noise_multiplier auto -num_features 30 -fraction_relevant_features 0.33 -num_shuffling_trials 100 -seed 13531 -condor 0 -shared_filesystem 1 -avoid_bad_hosts 1 -features_per_worker 1 -output_dir simulation_demo_toy8 -cleanup 0 -skip_synthesis 0 -evaluate_only 0

# Testing failed simulation - fixed with median loss statistic
# python -m anamod.simulation.simulation -num_instances 200 -sequence_length 50 -num_features 30 -fraction_relevant_features 0.33 -noise_multiplier auto -analysis_type temporal -model_type regressor -sequences_independent_of_windows 0 -perturbation shuffling -num_shuffling_trials 50 -num_interactions 0  -seed 500027 -output_dir temp1 -skip_synthesis 1 -cleanup 0

# Failed sim fixed with median loss statistic. Testing old failed simulation to verify it works with new statistic too - no, doesn't work, high FDR
# python -m anamod.simulation.simulation -num_instances 100 -model_type regressor -analysis_type temporal -sequence_length 50 -sequences_independent_of_windows 0 -perturbation shuffling -noise_multiplier auto -num_features 30 -fraction_relevant_features 0.33 -num_shuffling_trials 100 -seed 13531 -condor 0 -shared_filesystem 1 -avoid_bad_hosts 1 -features_per_worker 1 -output_dir simulation_demo_toy9 -cleanup 0 -skip_synthesis 0 -evaluate_only 0

# Testing failed simulations with log mean loss statistic - overall FDR ok for both, but window ordering FDR very bad
# python -m anamod.simulation.simulation -num_instances 200 -sequence_length 50 -num_features 30 -fraction_relevant_features 0.33 -noise_multiplier auto -analysis_type temporal -model_type regressor -sequences_independent_of_windows 0 -perturbation shuffling -num_shuffling_trials 50 -num_interactions 0  -seed 500027 -output_dir temp2 -skip_synthesis 0 -cleanup 0

# python -m anamod.simulation.simulation -num_instances 100 -model_type regressor -analysis_type temporal -sequence_length 50 -sequences_independent_of_windows 0 -perturbation shuffling -noise_multiplier auto -num_features 30 -fraction_relevant_features 0.33 -num_shuffling_trials 100 -seed 13531 -condor 0 -shared_filesystem 1 -avoid_bad_hosts 1 -features_per_worker 1 -output_dir simulation_demo_toy10 -cleanup 0 -skip_synthesis 0 -evaluate_only 0

# Testing failed simulations with mean loss statistic to check window ordering FDR - similar to median loss (good) or mean log loss (bad)? => seems to be bad
# python -m anamod.simulation.simulation -num_instances 200 -sequence_length 50 -num_features 30 -fraction_relevant_features 0.33 -noise_multiplier auto -analysis_type temporal -model_type regressor -sequences_independent_of_windows 0 -perturbation shuffling -num_shuffling_trials 50 -num_interactions 0  -seed 500027 -output_dir temp3 -skip_synthesis 0 -cleanup 0
# python -m anamod.simulation.simulation -num_instances 100 -model_type regressor -analysis_type temporal -sequence_length 50 -sequences_independent_of_windows 0 -perturbation shuffling -noise_multiplier auto -num_features 30 -fraction_relevant_features 0.33 -num_shuffling_trials 100 -seed 13531 -condor 0 -shared_filesystem 1 -avoid_bad_hosts 1 -features_per_worker 1 -output_dir simulation_demo_toy11 -cleanup 0 -skip_synthesis 0 -evaluate_only 0

# Repeating failed simulations with mean loss statistic to check window ordering FDR, after adding fix to avoid floating point error in permutation test p-value computation - seems to match earlier results
# python -m anamod.simulation.simulation -num_instances 200 -sequence_length 50 -num_features 30 -fraction_relevant_features 0.33 -noise_multiplier auto -analysis_type temporal -model_type regressor -sequences_independent_of_windows 0 -perturbation shuffling -num_shuffling_trials 50 -num_interactions 0  -seed 500027 -output_dir temp4 -skip_synthesis 0 -cleanup 0
# python -m anamod.simulation.simulation -num_instances 100 -model_type regressor -analysis_type temporal -sequence_length 50 -sequences_independent_of_windows 0 -perturbation shuffling -noise_multiplier auto -num_features 30 -fraction_relevant_features 0.33 -num_shuffling_trials 100 -seed 13531 -condor 0 -shared_filesystem 1 -avoid_bad_hosts 1 -features_per_worker 1 -output_dir simulation_demo_toy12 -cleanup 0 -skip_synthesis 0 -evaluate_only 0

# Repeating failed simulations with mean log loss statistic to check window ordering FDR after adding fix to avoid floating point error in permutation test p-value computation - works for both simulations, but seems to have high overall FDR with more instances
# python -m anamod.simulation.simulation -num_instances 200 -sequence_length 50 -num_features 30 -fraction_relevant_features 0.33 -noise_multiplier auto -analysis_type temporal -model_type regressor -sequences_independent_of_windows 0 -perturbation shuffling -num_shuffling_trials 50 -num_interactions 0  -seed 500027 -output_dir temp5 -skip_synthesis 0 -cleanup 0
# python -m anamod.simulation.simulation -num_instances 100 -model_type regressor -analysis_type temporal -sequence_length 50 -sequences_independent_of_windows 0 -perturbation shuffling -noise_multiplier auto -num_features 30 -fraction_relevant_features 0.33 -num_shuffling_trials 100 -seed 13531 -condor 0 -shared_filesystem 1 -avoid_bad_hosts 1 -features_per_worker 1 -output_dir simulation_demo_toy13 -cleanup 0 -skip_synthesis 0 -evaluate_only 0

# Repeating failed simulation with sign-based statistic - it appears that some features (e.g. 2) have outliers due to standardization that may be causing false positives for other irrelevant features
# python -m anamod.simulation.simulation -num_instances 200 -sequence_length 50 -num_features 30 -fraction_relevant_features 0.33 -noise_multiplier auto -analysis_type temporal -model_type regressor -sequences_independent_of_windows 0 -perturbation shuffling -num_shuffling_trials 50 -num_interactions 0  -seed 500027 -output_dir temp6 -skip_synthesis 1 -cleanup 0 -permutation_test_statistic sign_loss

# Repeating failed simulation with multiple statistics after adding squashing after standardization - same result: sign loss ok, mean loss high FDR
# python -m anamod.simulation.simulation -num_instances 200 -sequence_length 50 -num_features 30 -fraction_relevant_features 0.33 -noise_multiplier auto -analysis_type temporal -model_type regressor -sequences_independent_of_windows 0 -perturbation shuffling -num_shuffling_trials 50 -num_interactions 0  -seed 500027 -output_dir temp7 -skip_synthesis 0 -cleanup 0 -permutation_test_statistic sign_loss
# python -m anamod.simulation.simulation -num_instances 200 -sequence_length 50 -num_features 30 -fraction_relevant_features 0.33 -noise_multiplier auto -analysis_type temporal -model_type regressor -sequences_independent_of_windows 0 -perturbation shuffling -num_shuffling_trials 50 -num_interactions 0  -seed 500027 -output_dir temp8 -skip_synthesis 0 -cleanup 0 -permutation_test_statistic mean_loss

# Repeating failed simulation with multiple statistics after adding squashing after standardization
# python -m anamod.simulation.simulation -num_instances 200 -sequence_length 50 -num_features 30 -fraction_relevant_features 0.33 -noise_multiplier auto -analysis_type temporal -model_type regressor -sequences_independent_of_windows 0 -perturbation shuffling -num_shuffling_trials 50 -num_interactions 0  -seed 500027 -output_dir temp7 -skip_synthesis 1 -cleanup 0 -permutation_test_statistic sign_loss

# Fails with sign loss for feature 5 - debug
# python -m anamod.simulation.simulation -num_instances 200 -sequence_length 50 -num_features 30 -fraction_relevant_features 0.33 -noise_multiplier auto -analysis_type temporal -model_type regressor -sequences_independent_of_windows 0 -perturbation shuffling -num_shuffling_trials 250 -num_interactions 0  -seed 500027 -output_dir fail1_1 -skip_synthesis 1 -cleanup 0 -permutation_test_statistic sign_loss

# Variation for debugging
# python -m anamod.simulation.simulation -num_instances 200 -sequence_length 50 -num_features 30 -fraction_relevant_features 0.33 -noise_multiplier auto -analysis_type temporal -model_type regressor -sequences_independent_of_windows 0 -perturbation shuffling -num_shuffling_trials 500 -num_interactions 0  -seed 500027 -output_dir fail1_1 -skip_synthesis 1 -cleanup 0 -permutation_test_statistic sign_loss

# Variation for debugging
# python -m anamod.simulation.simulation -num_instances 500 -sequence_length 50 -num_features 30 -fraction_relevant_features 0.33 -noise_multiplier auto -analysis_type temporal -model_type regressor -sequences_independent_of_windows 0 -perturbation shuffling -num_shuffling_trials 10 -num_interactions 0  -seed 500027 -output_dir fail1_1 -skip_synthesis 0 -cleanup 0 -permutation_test_statistic sign_loss

# Rerun simulations with RNG deep copying fixed
# python -m anamod.simulation.simulation -num_instances 200 -sequence_length 50 -num_features 30 -fraction_relevant_features 0.33 -noise_multiplier auto -analysis_type temporal -model_type regressor -sequences_independent_of_windows 0 -perturbation shuffling -num_shuffling_trials 20 -num_interactions 0  -seed 500027 -output_dir fail1_3 -skip_synthesis 0 -cleanup 0

# python -m anamod.simulation.simulation -num_instances 200 -sequence_length 50 -num_features 30 -fraction_relevant_features 0.33 -noise_multiplier auto -analysis_type temporal -model_type regressor -sequences_independent_of_windows 0 -perturbation shuffling -num_shuffling_trials 20 -num_interactions 0  -seed 13531 -output_dir fail1_4 -skip_synthesis 0 -cleanup 0

# New failure
# python -m anamod.simulation.simulation -num_instances 200 -sequence_length 50 -num_features 30 -fraction_relevant_features 0.33 -noise_multiplier auto -analysis_type temporal -model_type regressor -sequences_independent_of_windows 0 -perturbation shuffling -num_shuffling_trials 50 -num_interactions 0  -seed 600007 -output_dir fail2_1 -skip_synthesis 0 -cleanup 0
# python -m anamod.simulation.simulation -num_instances 200 -sequence_length 50 -num_features 30 -fraction_relevant_features 0.33 -noise_multiplier auto -analysis_type temporal -model_type regressor -sequences_independent_of_windows 0 -perturbation shuffling -num_shuffling_trials 50 -num_interactions 0  -seed 600007 -output_dir fail2_2 -skip_synthesis 0 -cleanup 0 -standardize_features 0
# python -m anamod.simulation.simulation -num_instances 200 -sequence_length 50 -num_features 30 -fraction_relevant_features 0.33 -noise_multiplier auto -analysis_type temporal -model_type regressor -sequences_independent_of_windows 0 -perturbation shuffling -num_shuffling_trials 50 -num_interactions 0  -seed 600007 -output_dir fail2_1 -skip_synthesis 1 -cleanup 0
# python -m anamod.simulation.simulation -num_instances 500 -sequence_length 50 -num_features 30 -fraction_relevant_features 0.33 -noise_multiplier auto -analysis_type temporal -model_type regressor -sequences_independent_of_windows 0 -perturbation shuffling -num_shuffling_trials 50 -num_interactions 0  -seed 600007 -output_dir fail2_3 -skip_synthesis 1 -cleanup 0
# python -m anamod.simulation.simulation -num_instances 200 -sequence_length 50 -num_features 30 -fraction_relevant_features 0.33 -noise_multiplier auto -analysis_type temporal -model_type regressor -sequences_independent_of_windows 0 -perturbation shuffling -num_shuffling_trials 50 -num_interactions 0  -seed 600007 -output_dir fail2_4 -skip_synthesis 1 -cleanup 0 -permutation_test_statistic sign_loss

# Features 4 and 16 false positives (mean loss)
# python -m anamod.simulation.simulation -num_instances 1000 -sequence_length 50 -num_features 30 -fraction_relevant_features 0.33 -noise_multiplier auto -analysis_type temporal -model_type regressor -sequences_independent_of_windows 0 -perturbation shuffling -num_shuffling_trials 50 -num_interactions 0  -seed 600007 -output_dir fail2_5 -skip_synthesis 1 -cleanup 0
#python -m anamod.simulation.simulation -num_instances 1000 -sequence_length 50 -num_features 30 -fraction_relevant_features 0.33 -noise_multiplier auto -analysis_type temporal -model_type regressor -sequences_independent_of_windows 0 -perturbation shuffling -num_shuffling_trials 500 -num_interactions 0  -seed 600007 -output_dir fail2_6 -skip_synthesis 1 -cleanup 0
python -m anamod.simulation.simulation -num_instances 5000 -sequence_length 50 -num_features 30 -fraction_relevant_features 0.33 -noise_multiplier auto -analysis_type temporal -model_type regressor -sequences_independent_of_windows 0 -perturbation shuffling -num_shuffling_trials 50 -num_interactions 0  -seed 600007 -output_dir fail2_7 -skip_synthesis 0 -cleanup 0


# Another one, fails with sign loss
# python -m anamod.simulation.simulation -num_instances 1000 -sequence_length 50 -num_features 30 -fraction_relevant_features 0.33 -noise_multiplier auto -analysis_type temporal -model_type regressor -sequences_independent_of_windows 0 -perturbation shuffling -num_shuffling_trials 50 -num_interactions 0  -seed 600000 -output_dir fail3_1 -skip_synthesis 1 -cleanup 0 -permutation_test_statistic sign_loss
